// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaCare.Data;

#nullable disable

namespace PharmaCare.Migrations
{
    [DbContext(typeof(PharmacyContext))]
    [Migration("20230511163109_inial2")]
    partial class inial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaCare.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Drugs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 11, 22, 1, 9, 496, DateTimeKind.Local).AddTicks(5840),
                            DrugName = "Acetaminophen",
                            ExpiryDate = new DateTime(2084, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            price = 421f
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 11, 22, 1, 9, 496, DateTimeKind.Local).AddTicks(5855),
                            DrugName = "Doxycycline",
                            ExpiryDate = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            price = 321f
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 5, 11, 22, 1, 9, 496, DateTimeKind.Local).AddTicks(5857),
                            DrugName = "Lexapro",
                            ExpiryDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            price = 401f
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 5, 11, 22, 1, 9, 496, DateTimeKind.Local).AddTicks(5858),
                            DrugName = "Pantoprazole",
                            ExpiryDate = new DateTime(2031, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            price = 921f
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 5, 11, 22, 1, 9, 496, DateTimeKind.Local).AddTicks(5860),
                            DrugName = "secukinumab",
                            ExpiryDate = new DateTime(2027, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            price = 1123f
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 5, 11, 22, 1, 9, 496, DateTimeKind.Local).AddTicks(5862),
                            DrugName = "Wegovy",
                            ExpiryDate = new DateTime(2052, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            price = 891f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
